### PR TITLE
Add the missing deployment-enterprise Changelog

### PR DESCRIPTION
**Pull request by oleorhagen**
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
Ref: https://northern-tech.slack.com/archives/C0XM0KX9C/p1647441007912249

**Review by kjaskiewiczz — APPROVED** [review]

**Comment by oleorhagen** [comment]
Error stems from `b3ba969b61e7e701c8f6bb88b151c0191be5b062`

**Comment by oleorhagen** [comment]
It was `deviceauth-ent` which was supposed to be removed...

**Review by lluiscampos — CHANGES_REQUESTED** [review]
> It was `deviceauth-ent` which was supposed to be removed...

So please remove `deviceauth-enteterprise` in this PR :smiley:

**Comment by oleorhagen** [comment]
> > It was `deviceauth-ent` which was supposed to be removed...
> 
> So please remove `deviceauth-enteterprise` in this PR smiley

It's coming :p 

Reason I havent merged :lauging:

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
