### PR TITLE
Add all changelogs

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Review by tranchitella — APPROVED** [review]
Looks good... but how do you generate the individual changelogs?
Sorry for the dummy question, but I don't understand who is generating them, when and how.

**Comment by lluiscampos** [comment]
> Looks good... but how do you generate the individual changelogs?
> Sorry for the dummy question, but I don't understand who is generating them, when and how.

I have wrote an ugly Python script to do this. It is a one time operation (hence I waited until the releases were out) as from now on we will commit the changelog for the new releases into this repo.

**Comment by lluiscampos** [comment]
I pushed the script [here](https://github.com/lluiscampos/mender-docs/blob/split-changelog-python-script/202.Release-information/01.Release-notes-changelog/changelog_split.py) :see_no_evil:

**Comment by kacf** [comment]
Since it's split up differently now, I suppose we need to change the generator too. Perhaps it can piggyback off of the `independent_component` fields somehow...

**Comment by lluiscampos** [comment]
> Since it's split up differently now, I suppose we need to change the generator too. Perhaps it can piggyback off of the `independent_component` fields somehow...

Yes, that is my idea! Is part of the acceptance criteria of the task but I'll delay it couple of days more.

**Pull request merged**
